
KERAS_SUFFIX = ".keras"
NUMPY_SUFFIX = ".npy"

AMPLITUDE_RECONSTRUCTION_DATA_PATH = "../Data/"

ORIGINAL_FOLDER_DATA_PATH = f"{AMPLITUDE_RECONSTRUCTION_DATA_PATH}/OriginalData"
ORIGINAL_FLUXES_FOLDER = f"{ORIGINAL_FOLDER_DATA_PATH}/plfluxes_simplepoly__pllabdata_20230625a_superK_slmcube_20230625_complsines-01sp_04"
ORIGINAL_SLM_FOLDER = f"{ORIGINAL_FOLDER_DATA_PATH}/slmcube_20230625_complsines-01sp_04_PSFWFs_file"

PROCESSED_DATA_FOLDER = f"{AMPLITUDE_RECONSTRUCTION_DATA_PATH}/ProcessedData"
TRAIN_FOLDER = f"{PROCESSED_DATA_FOLDER}/TrainData"
PROCESSED_FLUXES_FC_FILE = f"{TRAIN_FOLDER}/processed_fluxes_fully_connected{NUMPY_SUFFIX}"


#OLD STUFF

FLUXES_FOLDER = f"{AMPLITUDE_RECONSTRUCTION_DATA_PATH}plfluxes_simplepoly__pllabdata_20230625a_superK_slmcube_20230625_complsines-01sp_04"
SLM_FOLDER = f"{AMPLITUDE_RECONSTRUCTION_DATA_PATH}/slmcube_20230625_complsines-01sp_04_PSFWFs_file"

FLUXES_FILE = "all_fluxes.npy"
AMPLITUDE_FILE = "complexsine_pupamp.npy"
PHASE_FILE = "complexsine_pupphase.npy"


MODELS_FOLDER_PATH = "./Models"
MODELS_DESCRIPTION_FILE_PATH = "./models_descriptions.txt"

