NUMPY_SUFFIX = ".npy"

HOME = "/home/dani"

PSF_MINIDATASET_PATH = f"{HOME}/DaniProjects/SAIL/PhotonicLanternProjects/Data/PSFReconstructionMinidataset"

ZERNIKE_COMPLEX_FIELDS_FILE_NAME = "zernike_complex_fields"
ZERNIKE_INTENSITIES_FILE_NAME = "zernike_intensities"
ZERNIKE_MODE_COEFFICIENTS_FILE_NAME = "zernike_mode_coefficients"
ZERNIKE_OUTPUT_FLUXES_FILE_NAME = "zernike_output_fluxes"
PROCESSED_ZERNIKE_OUTPUT_FLUXES_FILE_NAME = "processed_zernike_output_fluxes"
ZERNIKE_PSF_LP_MODES_FILE_NAME = "lp_modes_from_zernike_psf"
PROCESSED_ZERNIKE_PSF_LP_MODES_FILE_NAME = "processed_lp_modes_from_zernike_psf"

# Folders paths
ZERNIKE_COMPLEX_FIELDS_MINIDATASET_FOLDER_PATH = f"{PSF_MINIDATASET_PATH}/ZernikeComplexFields"
ZERNIKE_MODES_MINIDATASET_FOLDER_PATH = f"{PSF_MINIDATASET_PATH}/ZernikeModeCoefficients"
ZERNIKE_PSF_LP_MODES_MINIDATASET_FOLDER_PATH = f"{PSF_MINIDATASET_PATH}/LPModesFromZernikePSF"
ZERNIKE_OUTPUT_FLUXES_MINIDATASET_FOLDER_PATH = f"{PSF_MINIDATASET_PATH}/ZernikeOutputFluxes"

PROCESSED_ZERNIKE_PSF_LP_MODES_MINIDATASET_PATH = f"{PSF_MINIDATASET_PATH}/ProcessedLPModesFromZernikePSF"
PROCESSED_ZERNIKE_COMPLEX_FIELDS_MINIDATASET_PATH = f"{PSF_MINIDATASET_PATH}/ProcessedZernikeComplexFields"
PROCESSED_ZERNIKE_OUTPUT_FLUXES_MINIDATASET_PATH = f"{PSF_MINIDATASET_PATH}/ProcessedZernikeOutputFluxes"

# Files paths
ZERNIKE_2M_COMPLEX_FIELDS_MINIDATASET_FILE_PATH = f"{ZERNIKE_COMPLEX_FIELDS_MINIDATASET_FOLDER_PATH}/2M_{ZERNIKE_COMPLEX_FIELDS_FILE_NAME}{NUMPY_SUFFIX}"
ZERNIKE_2M_MODE_COEFFICIENTS_MINIDATASET_FILE_PATH = f"{ZERNIKE_MODES_MINIDATASET_FOLDER_PATH}/2M_{ZERNIKE_MODE_COEFFICIENTS_FILE_NAME}{NUMPY_SUFFIX}"
ZERNIKE_2M_PSF_LP_MODES_MINIDATASET_FILE_PATH = f"{ZERNIKE_PSF_LP_MODES_MINIDATASET_FOLDER_PATH}/2M_{ZERNIKE_PSF_LP_MODES_FILE_NAME}{NUMPY_SUFFIX}"
ZERNIKE_2M_OUTPUT_FLUXES_MINIDATASET_FILE_PATH = f"{ZERNIKE_OUTPUT_FLUXES_MINIDATASET_FOLDER_PATH}/2M_{ZERNIKE_OUTPUT_FLUXES_FILE_NAME}{NUMPY_SUFFIX}"

PROCESSED_ZERNIKE_2M_COMPLEX_FIELDS_INTENSITY_MINIDATASET_FILE_PREFIX = f"{PROCESSED_ZERNIKE_COMPLEX_FIELDS_MINIDATASET_PATH}/2M_{ZERNIKE_INTENSITIES_FILE_NAME}{NUMPY_SUFFIX}"

ZERNIKE_2M_PSF_LP_MODES_PCA_MINIDATASET_FILE_PATH = f"{PROCESSED_ZERNIKE_PSF_LP_MODES_MINIDATASET_PATH}/pca_{PROCESSED_ZERNIKE_PSF_LP_MODES_FILE_NAME}{NUMPY_SUFFIX}"
ZERNIKE_2M_PSF_LP_MODES_UMAP_MINIDATASET_FILE_PATH= f"{PROCESSED_ZERNIKE_PSF_LP_MODES_MINIDATASET_PATH}/umap_{PROCESSED_ZERNIKE_PSF_LP_MODES_FILE_NAME}{NUMPY_SUFFIX}"
ZERNIKE_2M_PSF_OUTPUT_FLUXES_PCA_MINIDATASET_FILE_PATH = f"{PROCESSED_ZERNIKE_OUTPUT_FLUXES_MINIDATASET_PATH}/pca_{PROCESSED_ZERNIKE_OUTPUT_FLUXES_FILE_NAME}{NUMPY_SUFFIX}"
ZERNIKE_2M_PSF_OUTPUT_FLUXES_UMAP_MINIDATASET_FILE_PATH= f"{PROCESSED_ZERNIKE_OUTPUT_FLUXES_MINIDATASET_PATH}/umap_{PROCESSED_ZERNIKE_OUTPUT_FLUXES_FILE_NAME}{NUMPY_SUFFIX}"
ZERNIKE_2M_PSF_INTENSITIES_PCA_MINIDATASET_FILE_PATH = f"{PROCESSED_ZERNIKE_OUTPUT_FLUXES_MINIDATASET_PATH}/pca_{ZERNIKE_INTENSITIES_FILE_NAME}{NUMPY_SUFFIX}"
ZERNIKE_2M_PSF_INTENSITIES_UMAP_MINIDATASET_FILE_PATH= f"{PROCESSED_ZERNIKE_OUTPUT_FLUXES_MINIDATASET_PATH}/umap_{ZERNIKE_INTENSITIES_FILE_NAME}{NUMPY_SUFFIX}"

PATHS_DICTIONARY = {
	"MINI_2M":{
		"complex_field_path": ZERNIKE_2M_COMPLEX_FIELDS_MINIDATASET_FILE_PATH,
		"intensities_file_path": PROCESSED_ZERNIKE_2M_COMPLEX_FIELDS_INTENSITY_MINIDATASET_FILE_PREFIX,
		"pca_intensities_path": ZERNIKE_2M_PSF_INTENSITIES_PCA_MINIDATASET_FILE_PATH,
		"umap_intensities_path": ZERNIKE_2M_PSF_INTENSITIES_UMAP_MINIDATASET_FILE_PATH,
		"zernike_mode_coefficients_path": ZERNIKE_2M_MODE_COEFFICIENTS_MINIDATASET_FILE_PATH,
		"lp_modes_path": ZERNIKE_2M_PSF_LP_MODES_MINIDATASET_FILE_PATH,
		"pca_lp_modes_path": ZERNIKE_2M_PSF_LP_MODES_PCA_MINIDATASET_FILE_PATH,
		"umap_lp_modes_path": ZERNIKE_2M_PSF_LP_MODES_UMAP_MINIDATASET_FILE_PATH,
		"pca_output_fluxes_path": ZERNIKE_2M_PSF_OUTPUT_FLUXES_PCA_MINIDATASET_FILE_PATH,
		"umap_output_fluxes_path": ZERNIKE_2M_PSF_OUTPUT_FLUXES_UMAP_MINIDATASET_FILE_PATH,
		"output_fluxes": ZERNIKE_2M_OUTPUT_FLUXES_MINIDATASET_FILE_PATH,
		"zernike_mode_indexes": [2, 3],
		"zernike_coefficients_range": [[1.8, 2],
									   [1.8, 2]],
		"labels_dictionary":{
			"pp":1,
			"pn":2,
			"np":3,
			"nn":4
		}
	}
}